# Generated by Django 2.0.3 on 2018-12-28 00:02

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=20, verbose_name='Senha')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('foto', models.ImageField(upload_to='')),
                ('dtExpiracao', models.DateField(default='1900-01-01', verbose_name='Data de Expiração')),
                ('tipo', models.CharField(default='C', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.ContasManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnoEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(default='Resposta Aberta', max_length=15)),
                ('extras', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('data', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 2, 59, 298627))),
                ('status', models.CharField(default='Aberta', max_length=7)),
                ('planoDeEnsino', models.TextField()),
                ('cargaHoraria', models.SmallIntegerField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('ementa', models.TextField()),
                ('conteudoProgramatico', models.TextField()),
                ('bibliografiaBasica', models.TextField()),
                ('bibliografiaComplementar', models.TextField()),
                ('percentualPratico', models.SmallIntegerField()),
                ('percentualTeorico', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=60)),
                ('Reposta', models.TextField()),
                ('DtEntrega', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 2, 59, 298627))),
                ('StatusEntrega', models.CharField(default='Entregue', max_length=9)),
                ('Nota', models.DecimalField(decimal_places=0, max_digits=3)),
                ('DtAvaliacao', models.DateField()),
                ('Obs', models.TextField(blank=True, null=True)),
                ('idAtividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('metodologia', models.TextField(null=True)),
                ('recursos', models.TextField(null=True)),
                ('criterioAvaliacao', models.TextField(null=True)),
                ('planoDeAulas', models.TextField(null=True)),
                ('descricao', models.TextField(null=True)),
                ('idAno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.AnoEnsino')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assunto', models.CharField(max_length=60)),
                ('Referencia', models.CharField(max_length=200)),
                ('Conteudo', models.TextField()),
                ('StatusMensagem', models.CharField(default='Entregue', max_length=10)),
                ('DTEnvio', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 2, 59, 298627))),
                ('DTResposta', models.DateTimeField(blank=True, null=True)),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DTSolicitacao', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 2, 59, 298627))),
                ('status', models.CharField(default='Solicitada', max_length=10)),
                ('idAno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.AnoEnsino')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ra', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.ContasManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assistente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ano', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.ContasManager()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ano', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.ContasManager()),
            ],
        ),
        migrations.AddField(
            model_name='solicitacaomatricula',
            name='idCoordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='idCoordenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='idCoordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='idDisciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='idHabilidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Habilidade'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='Coordenador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='turma',
            name='idProfessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='solicitacaomatricula',
            name='idAluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='idAluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='idAssistente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Assistente'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='idProfessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='idAluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='idAssistente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Assistente'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='idProfessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='idAssistente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Assistente'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='idProfessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor'),
        ),
    ]
