# Generated by Django 2.0.3 on 2018-12-28 00:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoensino',
            name='idCoordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 23, 36, 423383)),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='DtEntrega',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 23, 36, 423383)),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='DTEnvio',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 23, 36, 438983)),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='DTSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 22, 23, 36, 423383)),
        ),
    ]
