# Generated by Django 2.0.3 on 2018-12-30 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181230_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anoensino',
            name='nome',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='assistente',
            name='ano',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 14, 24, 53, 666048)),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='DtEntrega',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 14, 24, 53, 666048)),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='DTEnvio',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 14, 24, 53, 666048)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ano',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='DTSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 14, 24, 53, 666048)),
        ),
    ]
